import Reveal from '../components/Reveal';
import { Link } from 'react-router-dom';

export default function Sustainability() {
  return (
    <>
      {/* Page Hero */}
      <section className="page-hero noise">
        <div className="page-hero-bg">
          <img src="/gallery/plant-interior-reactors.jpg" alt="" aria-hidden="true" />
          <div className="page-hero-overlay" />
        </div>
        <div className="page-hero-content">
          <div className="container">
            <Reveal>
              <div className="eyebrow">Sustainability</div>
              <h1 className="text-h1">Building a Cleaner,<br/>Greener Future</h1>
              <p style={{ marginTop: '1rem', maxWidth: '54ch', color: 'var(--muted)', fontSize: '1.05rem', lineHeight: 1.8 }}>
                Environmental and social outcomes of responsible waste recovery — measurable, honest, verifiable.
              </p>
            </Reveal>
          </div>
        </div>
      </section>

      {/* Four Pillars */}
      <section className="section">
        <div className="container">
          <Reveal>
            <div className="eyebrow">Four Pillars</div>
            <h2 className="text-h2">Our sustainability framework.</h2>
            <p style={{ marginTop: '1rem', maxWidth: '56ch', color: 'var(--muted)', lineHeight: 1.8 }}>
              Every aspect of the CTD plant's design and operation is benchmarked against four
              measurable environmental and social outcomes.
            </p>
          </Reveal>

          <div style={{ marginTop: '3rem', display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(260px, 1fr))', gap: '1.25rem' }}>
            {[
              {
                icon: <Building2 />,
                title: 'Cleaner Cities',
                desc: 'Our plant diverts non-recyclable plastic away from urban landfills and open burning grounds — directly improving ambient air quality, groundwater safety, and urban land use in the cities that supply our feedstock.',
              },
              {
                icon: <Recycle />,
                title: 'Reduced Landfill',
                desc: 'The 80% of MSW plastic that mechanical recycling cannot process is the exact fraction our CTD plant targets. Every 6,000 kg processed per day is waste that no longer goes to a landfill or drain.',
              },
              {
                icon: <Leaf />,
                title: 'Resource Recovery',
                desc: 'Waste plastic becomes fuel oil for industry, carbon char for cement and steel plants, and process gas for internal energy — a true circular economy approach with zero net discharge from the plant.',
              },
              {
                icon: <Users />,
                title: 'Employment Support',
                desc: 'Direct employment in plant operations, quality control, and logistics. Indirect employment in waste collection, segregation at source, and transport — supporting the informal waste management sector.',
              },
            ].map((pillar, i) => (
              <Reveal key={i} delay={i * 100}>
                <div className="pillar-card" style={{ height: '100%' }}>
                  <div className="pillar-icon">{pillar.icon}</div>
                  <div className="pillar-title">{pillar.title}</div>
                  <p className="pillar-desc">{pillar.desc}</p>
                </div>
              </Reveal>
            ))}
          </div>
        </div>
      </section>

      {/* Impact Metrics */}
      <section className="section" style={{ borderTop: '1px solid var(--border)', background: 'var(--surface)' }}>
        <div className="container">
          <Reveal>
            <div className="eyebrow">Impact Metrics</div>
            <h2 className="text-h2" style={{ maxWidth: '18ch' }}>Honest claims, documented sources.</h2>
            <p style={{ marginTop: '1rem', maxWidth: '56ch', color: 'var(--muted)', lineHeight: 1.8 }}>
              All metrics below are drawn from company project documentation. We do not publish unverifiable superlatives.
            </p>
          </Reveal>

          <div style={{ marginTop: '3rem', display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(260px, 1fr))', gap: '1rem' }}>
            {[
              { label: 'Zero Liquid Discharge', sub: 'No wastewater generated by the CTD process itself', source: 'Company project documentation' },
              { label: 'Zero Other Discharge', sub: 'Every input becomes a product — fuel, carbon, or gas', source: 'Company project documentation' },
              { label: 'Energy-Positive Operation', sub: 'Process gas fuels the plant\'s own HAG burner system', source: 'Company technical documentation' },
              { label: '80% Non-Recyclable Target', sub: 'Specifically designed for the fraction recycling cannot handle', source: 'PDF: Project Profile for Plastic Waste Disposal' },
              { label: 'CPCB-Aligned Process', sub: 'Multi-stage wet scrubber, O₂ monitoring, nitrogen purging', source: 'Company project documentation' },
              { label: 'Make in India', sub: 'Plant design, manufacturing & R&D done entirely in India', source: 'Company profile documentation' },
            ].map((m, i) => (
              <Reveal key={i} delay={i * 80}>
                <div className="card">
                  <div style={{ fontFamily: 'var(--font-display)', fontWeight: 600, fontSize: '.95rem', marginBottom: '.35rem' }}>{m.label}</div>
                  <p style={{ fontSize: '.875rem', color: 'var(--muted)', lineHeight: 1.6, marginBottom: '.75rem' }}>{m.sub}</p>
                  <div style={{ fontSize: '.65rem', textTransform: 'uppercase', letterSpacing: '.12em', color: 'var(--muted-2)' }}>Source: {m.source}</div>
                </div>
              </Reveal>
            ))}
          </div>
        </div>
      </section>

      {/* MSW & Circular Economy */}
      <section className="section">
        <div className="container">
          <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(300px, 1fr))', gap: '4rem', alignItems: 'center' }}>
            <Reveal>
              <div className="eyebrow">Municipal Solid Waste</div>
              <h2 className="text-h2">Our role in the waste management chain.</h2>
              <p style={{ marginTop: '1rem', color: 'var(--muted)', lineHeight: 1.8 }}>
                Municipal solid waste consists of multiple fractions. Our CTD plant handles only the
                plastic fraction — specifically the non-recyclable portion that ends up in landfills today.
              </p>

              {/* MSW fraction breakdown */}
              <div style={{ marginTop: '2rem', display: 'flex', flexDirection: 'column', gap: '.75rem' }}>
                {[
                  { label: 'Organic / Wet Waste', pct: 50, color: '#8B6914' },
                  { label: 'Paper & Cardboard', pct: 15, color: '#6B7280' },
                  { label: 'Plastic (Total)', pct: 20, color: '#3D8B4A', highlight: true },
                  { label: 'Glass', pct: 5, color: '#4B8DAB' },
                  { label: 'Metal', pct: 5, color: '#9CA3AF' },
                  { label: 'Other', pct: 5, color: '#6B7280' },
                ].map(item => (
                  <div key={item.label}>
                    <div style={{ display: 'flex', justifyContent: 'space-between', fontSize: '.8rem', marginBottom: '.3rem' }}>
                      <span style={{ color: item.highlight ? 'var(--fg)' : 'var(--muted)', fontWeight: item.highlight ? 600 : 400 }}>
                        {item.label} {item.highlight && <span style={{ color: 'var(--primary-light)', fontSize: '.65rem', marginLeft: '.4rem' }}>← CTD Target</span>}
                      </span>
                      <span style={{ color: 'var(--muted)', fontFamily: 'var(--font-mono)' }}>~{item.pct}%</span>
                    </div>
                    <div style={{ height: '6px', background: 'rgba(255,255,255,.06)', borderRadius: '3px', overflow: 'hidden' }}>
                      <div style={{ width: `${item.pct * 4}%`, height: '100%', background: item.color, borderRadius: '3px', opacity: item.highlight ? 1 : 0.5 }} />
                    </div>
                  </div>
                ))}
              </div>
              <p style={{ marginTop: '1.25rem', fontSize: '.8rem', color: 'var(--muted-2)' }}>* Illustrative composition. Actual fractions vary by city and season.</p>
            </Reveal>

            <Reveal delay={150}>
              <div className="plant-img-wrap" style={{ aspectRatio: '4/3' }}>
                <img src="/gallery/plant-exterior-night.jpg" alt="T & M Industries CTD plant" loading="lazy" />
              </div>
            </Reveal>
          </div>
        </div>
      </section>

      {/* Health & Environment */}
      <section className="section" style={{ borderTop: '1px solid var(--border)', background: 'var(--surface)' }}>
        <div className="container">
          <Reveal>
            <div className="eyebrow">Health &amp; Environment</div>
            <h2 className="text-h2" style={{ maxWidth: '20ch' }}>Eliminating open burning and landfill pollution.</h2>
            <p style={{ marginTop: '1rem', maxWidth: '56ch', color: 'var(--muted)', lineHeight: 1.8 }}>
              The alternatives to proper plastic waste disposal — open burning and landfilling — carry severe
              and documented health and environmental consequences.
            </p>
          </Reveal>

          <div style={{ marginTop: '3rem', display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(260px, 1fr))', gap: '1rem' }}>
            {[
              { icon: <Wind />, label: 'Air Quality', positive: 'CTD eliminates open burning', negative: 'Open burning generates dioxins, furans, and PM2.5 particulates linked to respiratory disease' },
              { icon: <Droplets />, label: 'Groundwater', positive: 'Zero liquid discharge from CTD', negative: 'Landfill plastic leaches BPA, phthalates, and micro-plastics into soil and groundwater over decades' },
              { icon: <Mountain />, label: 'Land Use', positive: 'Reduces landfill footprint', negative: 'Plastic persists in landfill for 200–400 years, occupying land and degrading surrounding ecosystems' },
            ].map((item, i) => (
              <Reveal key={i} delay={i * 100}>
                <div className="card" style={{ height: '100%' }}>
                  <div style={{ color: 'var(--primary-light)', marginBottom: '1rem' }}>{item.icon}</div>
                  <div style={{ fontFamily: 'var(--font-display)', fontWeight: 600, marginBottom: '1rem' }}>{item.label}</div>
                  <div style={{ display: 'flex', flexDirection: 'column', gap: '.75rem' }}>
                    <div style={{ display: 'flex', gap: '.5rem', fontSize: '.875rem', color: 'var(--primary-light)' }}>
                      <span style={{ flexShrink: 0 }}>✓</span> {item.positive}
                    </div>
                    <div style={{ display: 'flex', gap: '.5rem', fontSize: '.875rem', color: 'var(--muted)', lineHeight: 1.6 }}>
                      <span style={{ flexShrink: 0, color: '#fc8181' }}>✕</span> {item.negative}
                    </div>
                  </div>
                </div>
              </Reveal>
            ))}
          </div>
        </div>
      </section>

      {/* CTA */}
      <section className="section">
        <div className="container">
          <Reveal>
            <div className="cta-band noise">
              <div className="cta-band-bg">
                <img src="/gallery/plant-interior-reactors.jpg" alt="" aria-hidden="true" />
                <div className="cta-band-overlay" />
              </div>
              <div className="cta-band-content">
                <div style={{ fontSize: '.7rem', textTransform: 'uppercase', letterSpacing: '.22em', color: 'var(--primary-light)' }}>
                  Municipal &amp; Industrial Partnerships
                </div>
                <h3 style={{ marginTop: '1rem', fontSize: 'clamp(1.75rem, 3vw, 3rem)', fontFamily: 'var(--font-display)', fontWeight: 700, lineHeight: 1.1 }}>
                  Partner with us for cleaner cities.
                </h3>
                <p style={{ marginTop: '1rem', color: 'var(--muted)', maxWidth: '42ch' }}>
                  Municipal bodies, industrial waste generators, and sustainability-focused investors —
                  contact us to discuss how CTD plants can address your plastic waste streams.
                </p>
                <Link to="/contact" className="btn btn-primary" style={{ marginTop: '2rem' }}>
                  <span>Get in Touch</span>
                  <ArrowRight size={16} />
                </Link>
              </div>
            </div>
          </Reveal>
        </div>
      </section>
    </>
  );
}

function Building2() { return <svg width={28} height={28} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round"><path d="M6 22V5a2 2 0 0 1 2-2h8a2 2 0 0 1 2 2v17"/><path d="M6 12H4a2 2 0 0 0-2 2v6a2 2 0 0 0 2 2h16a2 2 0 0 0 2-2v-6a2 2 0 0 0-2-2h-2"/><path d="M10 8h4M10 12h4M14 21v-3a2 2 0 0 0-4 0v3"/></svg>; }
function Recycle() { return <svg width={28} height={28} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round"><path d="M7 19H4.815a1.83 1.83 0 0 1-1.57-.881 1.785 1.785 0 0 1-.004-1.784L7.196 9.5"/><path d="M11 19h8.203a1.83 1.83 0 0 0 1.556-.89 1.784 1.784 0 0 0 0-1.775l-1.226-2.12"/><path d="m14 16-3 3 3 3"/><path d="M8.293 13.596 7.196 9.5 3.1 10.598"/><path d="m9.344 5.811 1.093-1.892A1.83 1.83 0 0 1 11.985 3a1.784 1.784 0 0 1 1.546.888l3.943 6.843"/><path d="m13.378 9.633 4.096 1.098 1.097-4.096"/></svg>; }
function Leaf() { return <svg width={28} height={28} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round"><path d="M11 20A7 7 0 0 1 9.8 6.1C15.5 5 17 4.48 19 2c1 2 2 4.18 2 8 0 5.5-4.78 10-10 10Z"/><path d="M2 21c0-3 1.85-5.36 5.08-6C9.5 14.52 12 13 13 12"/></svg>; }
function Users() { return <svg width={28} height={28} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round"><path d="M16 21v-2a4 4 0 0 0-4-4H6a4 4 0 0 0-4 4v2"/><circle cx="9" cy="7" r="4"/><path d="M22 21v-2a4 4 0 0 0-3-3.87M16 3.13a4 4 0 0 1 0 7.75"/></svg>; }
function Wind() { return <svg width={22} height={22} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round"><path d="M12.8 19.6A2 2 0 1 0 14 16H2"/><path d="M17.5 8a2.5 2.5 0 1 1 2 4H2"/><path d="M9.8 4.4A2 2 0 1 1 11 8H2"/></svg>; }
function Droplets() { return <svg width={22} height={22} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round"><path d="M7 16.3c2.2 0 4-1.83 4-4.05 0-1.16-.57-2.26-1.71-3.19S7.29 6.75 7 5.3c-.29 1.45-1.14 2.84-2.29 3.76S3 11.1 3 12.25c0 2.22 1.8 4.05 4 4.05z"/><path d="M12.56 6.6A10.97 10.97 0 0 0 14 3.02c.5 2.5 2 4.9 4 6.5s3 3.5 3 5.5a6.98 6.98 0 0 1-11.91 4.97"/></svg>; }
function Mountain() { return <svg width={22} height={22} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round"><path d="m8 3 4 8 5-5 5 15H2L8 3z"/></svg>; }
function ArrowRight({ size }: { size: number }) { return <svg width={size} height={size} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round"><path d="M5 12h14m-7-7 7 7-7 7"/></svg>; }
